name: cc-exam
channels:
  - defaults
dependencies:
  - python=3.12
  - myst-parser
  - sphinx
  - sphinx-autoapi
  - sphinx-autobuild
  - sphinx-rtd-theme
  - pip
  - h5py
  - black
  - isort
  - jupyterlab
  - numpy
  - pandas
  - pytest
  - ruff
  - scalene
  pip:
    - torch
    - torchvision
prefix: /opt/miniconda3/envs/cc-exam

